In [2]:
import pandas as pd
d=[10,20,30,40,50]
s=pd.Series(d)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [4]:
import pandas as pd
d=[10,20,30,40,'A']
s=pd.Series(d)
print(s)

0    10
1    20
2    30
3    40
4     A
dtype: object


In [10]:
d=[1,2,3,4]
i=['A','B','C','D']
s=pd.Series(d,index=i)
print(s)

A    1
B    2
C    3
D    4
dtype: int64


In [14]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota

In [16]:
d={'a':10,'b':20,'c':30}
s=pd.Series(d)
print(s)

a    10
b    20
c    30
dtype: int64


In [18]:
import numpy as np
d=np.array([100,200,300,400])
s=pd.Series(d,index=['a','b','c','d'])
print(s)

a    100
b    200
c    300
d    400
dtype: int32


In [26]:
import pandas as pd
d={'Name':['Alice','Bob','Raju Danger'],'Age':[25,30,34],'Country':['USA','UK','AUS']}
df=pd.DataFrame(d)
print(df)

          Name  Age Country
0        Alice   25     USA
1          Bob   30      UK
2  Raju Danger   34     AUS


In [22]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df=pd.DataFrame(array,columns=['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [28]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df=pd.DataFrame(array)
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [30]:
d=[[1,'Alice',25],[2,'Bob',30],[3,'Mary',34]]
print(d)
df=pd.DataFrame(d,columns=['ID','Name','Age'])
print(df)

[[1, 'Alice', 25], [2, 'Bob', 30], [3, 'Mary', 34]]
   ID   Name  Age
0   1  Alice   25
1   2    Bob   30
2   3   Mary   34


In [36]:
idf=pd.read_csv('iris_dataset.csv')
print(idf)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0    

In [46]:
idf=pd.read_excel('iris.xls')
print(idf)

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.